# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@opencode-ai/plugin@1.0.144" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-1.0.144.tgz";
    hash = "sha512-WMnoNyiyq4P3VVXURFm3HmN7slRd+1J8NxNbXTaCj64ooUI6BxZw5S9EcbC2On2WFQPHjEK0FOKrxu9WGg6+TA==";
  };
  "@opencode-ai/sdk@1.0.144" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-1.0.144.tgz";
    hash = "sha512-ryu08BT86Eo5OPMDxy19b2A9AHI0GtNp50ftq5Cp/ulV1xvLhB0fKAGRgWpWfj1iYVfGcQTd1a8kFvH8mK177Q==";
  };
  "@types/bun@1.3.4" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.4.tgz";
    hash = "sha512-EEPTKXHP+zKGPkhRLv+HI0UEX8/o+65hqARxLy8Ov5rIxMBPNTjeZww00CIihrIQGEQBYg+0roO5qOnS/7boGA==";
  };
  "@types/node@25.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.0.0.tgz";
    hash = "sha512-rl78HwuZlaDIUSeUKkmogkhebA+8K1Hy7tddZuJ3D0xV8pZSfsYGTsliGUol1JPzu9EKnTxPC4L1fiWouStRew==";
  };
  "argparse@1.0.10" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
    hash = "sha512-o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
  };
  "bun-types@1.3.4" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.4.tgz";
    hash = "sha512-5ua817+BZPZOlNaRgGBpZJOSAQ9RQ17pkwPD0yR7CfJg+r8DgIILByFifDTa+IPDDxzf5VNhtNlcKqFzDgJvlQ==";
  };
  "esprima@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
    hash = "sha512-eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
  };
  "extend-shallow@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
    hash = "sha512-zCnTtlxNoAiDc3gqY2aYAWFx7XWWiasuF2K8Me5WbN8otHKTUKBwjPtNpRs/rbUZm7KxWAaNj7P1a/p52GbVug==";
  };
  "gray-matter@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/gray-matter/-/gray-matter-4.0.3.tgz";
    hash = "sha512-5v6yZd4JK3eMI3FqqCouswVqwugaA9r4dNZB1wwcmrD02QkV5H0y7XBQW8QwQqEaZY1pM9aqORSORhJRdNK44Q==";
  };
  "ignore@7.0.5" = fetchurl {
    url = "https://registry.npmjs.org/ignore/-/ignore-7.0.5.tgz";
    hash = "sha512-Hs59xBNfUIunMFgWAbGX5cq6893IbWg4KnrjbYwX3tx0ztorVgTDA6B2sxf8ejHJ4wz8BqGUMYlnzNBer5NvGg==";
  };
  "is-extendable@0.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
    hash = "sha512-5BMULNob1vgFX6EjQw5izWDxrecWK9AM72rugNr0TFldMOi0fj6Jk+zeKIt0xGj4cEfQIJth4w3OKWOJ4f+AFw==";
  };
  "js-yaml@3.14.2" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.2.tgz";
    hash = "sha512-PMSmkqxr106Xa156c2M265Z+FTrPl+oxd/rgOQy2tijQeK5TxQ43psO1ZCwhVOSdnn+RzkzlRz/eY4BgJBYVpg==";
  };
  "kind-of@6.0.3" = fetchurl {
    url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
    hash = "sha512-dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
  };
  "section-matter@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/section-matter/-/section-matter-1.0.0.tgz";
    hash = "sha512-vfD3pmTzGpufjScBh50YHKzEu2lxBWhVEHsNGoEXmCmn2hKGfeNLYMzCJpe8cD7gqX7TJluOVpBkAequ6dgMmA==";
  };
  "sprintf-js@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
    hash = "sha512-D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
  };
  "strip-bom-string@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-bom-string/-/strip-bom-string-1.0.0.tgz";
    hash = "sha512-uCC2VHvQRYu+lMh4My/sFNmF2klFymLX1wHJeXnbEJERpV/ZsVuonzerjfrGpIGF7LBVa1O7i9kjiWvJiFck8g==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
  };
  "zod@4.1.13" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.13.tgz";
    hash = "sha512-AvvthqfqrAhNH9dnfmrfKzX5upOdjUVJYFqNSlkmGf64gRaTzlPwz99IHYnVs28qYAybvAlBV+H7pn0saFY4Ig==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}
